version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  db:
    image: mysql
    container_name: mysql_ecovair
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - dev

  phpmyadmin:
    image: real_phpmyadmin
    container_name: php_my_admin_ecovair
    restart: always
    depends_on:
      - db
    ports:
      - 8084:80
    environment:
      PMA_HOST : db
    networks:
      - dev

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:25"
      - "1080:1080"

networks:
  dev:

volumes:
  db-data: